In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
cell = tf.contrib.rnn.BasicLSTMCell(5)

In [4]:
cell_2 = tf.contrib.rnn.BasicRNNCell(5)

In [5]:
rand_inputs = np.random.normal(size=[1,5,1])

In [6]:
inputs = tf.constant(rand_inputs,dtype=tf.float32)

In [7]:
zero_state_1 = cell.zero_state(1,dtype=tf.float32)
zero_state_2 = cell_2.zero_state(1,dtype=tf.float32)

In [8]:
states_1 = []
outputs_1 = []
states_2 = []
outputs_2 = []

In [9]:
state_1 = zero_state_1
state_2 = zero_state_2

In [11]:
out,state_1 = cell(inputs[:,0,:],state_1)
outputs_1.append(out)
states_1.append(state_1)

out,state_2 = cell_2(inputs[:,0,:],state_2)
outputs_2.append(out)
states_2.append(state_2)

In [ ]:
out

In [18]:
for i in range(4):
    with tf.variable_scope('',reuse=True):
        out,state_1 = cell(inputs[:,i,:],state_1)
        outputs_1.append(out)
        states_1.append(state_1)

        out,state_2 = cell_2(inputs[:,i,:],state_2)
        outputs_2.append(out)
        states_2.append(state_2)

In [20]:
sess = tf.Session()

In [21]:
sess.run(tf.global_variables_initializer())

In [22]:
o1,s1,o2,s2 = sess.run([outputs_1,states_1,outputs_2,states_2])

In [23]:
o1

[array([[-0.07326134,  0.10881981, -0.02529788, -0.04072704,  0.04875959]], dtype=float32),
 array([[-0.12587196,  0.18593994, -0.0391391 , -0.0593419 ,  0.09171139]], dtype=float32),
 array([[-0.09905403,  0.13353604, -0.01861813, -0.01272955,  0.09385069]], dtype=float32),
 array([[-0.05724905,  0.07982526, -0.00863106,  0.02325895,  0.08229562]], dtype=float32),
 array([[-0.0744626 ,  0.12995736, -0.02473935,  0.01757095,  0.08873173]], dtype=float32)]

In [24]:
s1

[LSTMStateTuple(c=array([[-0.16547431,  0.20577541, -0.04365608, -0.07370391,  0.10478324]], dtype=float32), h=array([[-0.07326134,  0.10881981, -0.02529788, -0.04072704,  0.04875959]], dtype=float32)),
 LSTMStateTuple(c=array([[-0.28525621,  0.35801736, -0.06508203, -0.10567175,  0.2056445 ]], dtype=float32), h=array([[-0.12587196,  0.18593994, -0.0391391 , -0.0593419 ,  0.09171139]], dtype=float32)),
 LSTMStateTuple(c=array([[-0.19699425,  0.26796877, -0.03451995, -0.02460403,  0.20030063]], dtype=float32), h=array([[-0.09905403,  0.13353604, -0.01861813, -0.01272955,  0.09385069]], dtype=float32)),
 LSTMStateTuple(c=array([[-0.1127521 ,  0.15863648, -0.01667928,  0.04612409,  0.17052206]], dtype=float32), h=array([[-0.05724905,  0.07982526, -0.00863106,  0.02325895,  0.08229562]], dtype=float32)),
 LSTMStateTuple(c=array([[-0.16085023,  0.24881624, -0.04404178,  0.03270273,  0.19010496]], dtype=float32), h=array([[-0.0744626 ,  0.12995736, -0.02473935,  0.01757095,  0.08873173]], dt

In [25]:
o2

[array([[-0.72587937, -0.2983973 , -0.7004146 ,  0.20106703, -0.70973361]], dtype=float32),
 array([[-0.91679907, -0.16630068, -0.85630894, -0.06386018, -0.93637562]], dtype=float32),
 array([[-0.52485359,  0.12544559, -0.26522875, -0.21261024, -0.76199847]], dtype=float32),
 array([[-0.170678  ,  0.1929428 ,  0.11755153, -0.14186695, -0.37004018]], dtype=float32),
 array([[-0.54856217, -0.05733436, -0.37367839,  0.0634787 , -0.5495981 ]], dtype=float32)]

In [27]:
s2

[array([[-0.72587937, -0.2983973 , -0.7004146 ,  0.20106703, -0.70973361]], dtype=float32),
 array([[-0.91679907, -0.16630068, -0.85630894, -0.06386018, -0.93637562]], dtype=float32),
 array([[-0.52485359,  0.12544559, -0.26522875, -0.21261024, -0.76199847]], dtype=float32),
 array([[-0.170678  ,  0.1929428 ,  0.11755153, -0.14186695, -0.37004018]], dtype=float32),
 array([[-0.54856217, -0.05733436, -0.37367839,  0.0634787 , -0.5495981 ]], dtype=float32)]

In [28]:
x = np.ones([5,6])

In [29]:
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [31]:
z = tf.Variable(initial_value=x,dtype=tf.float32)

In [32]:
sess.run(tf.global_variables_initializer())

In [33]:
z

<tf.Variable 'Variable_1:0' shape=(5, 6) dtype=float32_ref>

In [34]:
sess.run(z)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [35]:
t = tf.Variable(initial_value=x,dtype=tf.float32)

In [36]:
sess.run(t)

FailedPreconditionError: Attempting to use uninitialized value Variable_2
	 [[Node: Variable_2/_32 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3_Variable_2", _device="/job:localhost/replica:0/task:0/gpu:0"](Variable_2)]]
	 [[Node: Variable_2/_33 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3_Variable_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]